### ISSUE TITLE
what version am i supposed to be using?

### ISSUE THREAD

**Issue by merrychrishna** [NineWorlds/serenity-android#450]
what version am i supposed to be using? is there a link to the newest working verion?

**Comment by merrychrishna** [comment]
its not connecting to my plex server so i must have the wrong version. can i get some help? im on android 9 beelink gt king box.

**Comment by kingargyle** [comment]
@merrychrishna  Plex support has been deprecated for a while.  Serenity was originally written for plex before 1.0.0 was released, but hasn't been kept up to date due to Plex not providing a truly documented.   All current Serenity 2.1.x or higher versions work best with the Emby Media server which provides similar functionality to Plex but with an Open Source API that is documented.
